### ISSUE TITLE
JWT, CORS 이슈 해결

### ISSUE THREAD

**Issue by sohnjunior** [sohnjunior/Yangpa-Market#2]
JWT, CORS 문제 해결을 위한 라이브러리 사용

**Comment by sprical408** [comment]
진행상황

현재 master에 커밋된 상태의 코드에서 sequelize 관련 오류가 있어, jwt에 대한 테스트 불가
이에 임의의 새로운 프로젝트를 생성해 따로 구현함

구현 내용 : 토큰 발급, 유효성 확인, 리미터

**Comment by sohnjunior** [comment]
Sequelize 어떤 오류 발생하나요?

**Comment by sprical408** [comment]
[https://stackoverflow.com/questions/58593200/deprecationwarning-a-boolean-value-was-passed-to-options-operatorsaliases-this](url)

참고하여 관련 오류는 해결했는데, 추가로 'config.json'의 root에 대한 password가 잘못 쓰인듯

![image](https://user-images.githubusercontent.com/52950532/83100385-ce2bf480-a0ea-11ea-8b60-b994ffa19a30.png)

**Comment by sohnjunior** [comment]
1. 로컬에 mysql 설치 및 database 생성 (database 이름은 yangpa로 하면됨)
2. mysql root 유저 비밀번호로 config.json 변경

이렇게 해보실래요?
깜빡하고 config 폴더를 gitignore에 포함 못시켜서 다시 push 할게요
config 폴더는 본인 로컬 환경에서 관리해주세요
