### ISSUE TITLE
회원관리 API 구현

### ISSUE THREAD

**Issue by sohnjunior** [sohnjunior/Yangpa-Market#9]
회원가입, 로그인, 로그아웃, 비밀번호 변경 API 구현
Passport 모듈 쓰면 됨

**Comment by sprical408** [comment]
참고 사이트
https://github.com/mikenicholson/passport-jwt
https://medium.com/devc-kano/basics-of-authentication-using-passport-and-jwt-with-sequelize-and-mysql-database-748e09d01bab
http://www.passportjs.org/docs/login/

현재 진행완료 사항
register를 통한 새로운 유저 등록
login을 통한, user 테이블에 등록된 유저인지 확인 후 jwt 토큰 발급

진행 중 사항(막힌 부분)
jwt 토큰을 발급 후 해당 유저로 진행할 때, 토큰 인증 관련 API를 생성하는 과정
passport-jwt의 jwtStrategy에 따라 만들었지만, 해당 토큰을 받게 하는 과정에서 막혀있음

**Comment by sohnjunior** [comment]
토큰은 발급되는데 인증이 안되는건가요??
